### ISSUE TITLE
template vars are missing scope

### ISSUE THREAD

**Issue by ThomasLohner** [sbitio/puppet-monit#11]
I'm using this module with a puppet master 3.8.6 and i get lots of these errors:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Failed to parse template monit/check/common.erb:
  Filepath: /etc/puppet/modules/monit/templates/check/common.erb
  Line: 2
  Detail: undefined method `empty?' for nil:NilClass
 at /etc/puppet/modules/monit/manifests/check/instance.pp:33:16
```

This template is called by various defines which don't have a local variable called  `alerts`, yet in the template you try to access `@alterts`. Wouldn't the correct way be `scope['monit::alerts']`?

The same issue happens in /etc/monit/monitrc:

```
include /*
```

In the template it says `include <%= @conf_dir %>/*` and it's called from monit::config but there is no local param `conf_dir` in this class. Changing the template to `include <%= scope['monit::conf_dir'] %>/*` fixes this problem.

**Comment by jonhattan** [comment]
Thanks for the report @ThomasLohner. Just fixed puppet 4 support in commits f1b2bdc15a460f5d4e4a7b09fddaa4d965292d9e, a0c9958d7f4c616313e199665efd655fefd8d87d and bebeea4711bb34f613b7783d5ea45d96fbfbdc76

**Comment by jonhattan** [comment]
I meant puppet 4 / future parser / all deprecations-as-errors they use to introduce in minor versions (!)

**Comment by jonhattan** [comment]
For the record, the change introduced in f1b2bdc breaks the module for puppet 3.8 in this way: https://tickets.puppetlabs.com/browse/PUP-4328 (last 5-6 comments). @ThomasLohner are you experiencing the same?

**Comment by jonhattan** [comment]
It happens when for example you don't give a value to `monit::swap` and `undef` is used as a literal string in erb.

**Comment by ThomasLohner** [comment]
I had to disable system checks with `monit::system_check_ensure: absent`, it's causing problems in OpenVZ Containers, which i'm using. For example there is no swap in the container...

Despite of this everything else works just fine on pupet 3.8.3. with future parser. Let me know if i can help somehow.
